---
- hosts: localhost
  gather_facts: false
  connection: local
  user: remote
  become: false

  vars: 
    kivy_version: 1.9.1
    kivy_7zip: Kivy-{{ kivy_version }}-osx-python2.7z

  tasks:

  - name: install p7zip
    homebrew: name=p7zip state=present
    when: ansible_distribution == 'MacOSX'

  - name: download kivy 
    get_url:
      url: https://kivy.org/downloads/{{ kivy_version }}/{{ kivy_7zip }}
      dest: /tmp/Kivy-{{ kivy_version }}-osx-python2.7z
      mode: 0755
    when: ansible_distribution == 'MacOSX'

  - name: extracting 7zip
    shell: 7z x {{ kivy_7zip }}
    args:
      chdir: /tmp
      creates: /tmp/Kivy2.app
    when: ansible_distribution == 'MacOSX'
 
  - name: rsync Kivy2.app into /Applications
    synchronize: src=/tmp/Kivy2.app dest=/Applications
    when: ansible_distribution == 'MacOSX'

  - name: create symlink to kivy
    file: 
      src: /Applications/Kivy2.app/Contents/Resources/script 
      dest: /usr/local/bin/kivy
      state: link
    when: ansible_distribution == 'MacOSX'
      