---
- hosts: localhost
  gather_facts: false
  connection: local
  user: remote
  become: false

  vars: 
    kivy_7zip: Kivy-1.9.1-osx-python2.7z

  tasks:

  - name: install p7zip
    homebrew: name=p7zip state=present
    when: ansible_distribution == 'MacOSX'

  - name: download kivy 
    get_url:
      url: https://kivy.org/downloads/1.9.1/{{ kivy_7zip }}
      dest: /tmp/Kivy-1.9.1-osx-python2.7z
      mode: 0755
    when: ansible_distribution == 'MacOSX'

  - name: extracting 7zip
    shell: 7z x {{ kivy_7zip }}
    args:
      chdir: /tmp
      creates: /tmp/Kivy2.app
 