---
- hosts: localhost
  gather_facts: true
  connection: local
  user: remote
  become: false

  vars: 
    kivy_version: 1.9.1
    kivy_7zip: Kivy-{{ kivy_version }}-osx-python2.7z

  tasks:

  - include: install-kivy-mac.yml
    when: ansible_distribution == 'MacOSX'

  - include: install-kivy-fedora.yml
    when: when: ansible_distribution == 'Fedora

